name = "hnauto606"
compatibility_date = "2026-08-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hnauto606-production"
database_id = "255bf58e-33f6-42dc-99a5-a6f3ae1ab4be"
preview_database_id = "7235c263-d567-481e-8492-f183f539a4b7"

[[r2_buckets]]
binding = "FILES"
bucket_name = "hnauto606-private-files"

[vars]
AUTH_MODE = "cloudflare-access"
VAPID_PUBLIC_KEY = "BKyiyC5A_gpgmpTFgfM7xWvbYV_VJYfVFXSuKMFTPcjhO4ghQ-Eya35cUY5aZuRUez3zP6aris0qhcWrbF3qJwc"
ALLOW_DEMO_AUTH = "false"
ALLOW_ANONYMOUS_WRITES = "true"
