PRAGMA foreign_keys = ON;

CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','staff','viewer')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE parking_zones (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, short_name TEXT NOT NULL, zone_type TEXT NOT NULL CHECK(zone_type IN ('parking','service')), sort_order INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE parking_spots (id TEXT PRIMARY KEY, zone_id TEXT NOT NULL REFERENCES parking_zones(id), label TEXT NOT NULL, current_vehicle_id TEXT UNIQUE, version INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(zone_id,label));
CREATE TABLE vehicles (id TEXT PRIMARY KEY, plate TEXT NOT NULL, model TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '', memo TEXT NOT NULL DEFAULT '', current_spot_id TEXT UNIQUE REFERENCES parking_spots(id), checked_in_at TEXT, checked_out_at TEXT, version INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX idx_vehicles_active_plate ON vehicles(plate) WHERE checked_out_at IS NULL;
CREATE INDEX idx_vehicles_plate ON vehicles(plate); CREATE INDEX idx_vehicles_current_spot ON vehicles(current_spot_id);
CREATE TABLE parking_movements (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id), movement_type TEXT NOT NULL CHECK(movement_type IN ('check_in','move','service','check_out')), from_spot_id TEXT REFERENCES parking_spots(id), to_spot_id TEXT REFERENCES parking_spots(id), actor_user_id TEXT NOT NULL REFERENCES users(id), note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_movements_vehicle_created ON parking_movements(vehicle_id,created_at DESC);
CREATE TABLE vehicle_status (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id), status_type TEXT NOT NULL CHECK(status_type IN ('battery','fuel','key','engine','tire','urea','other')), active INTEGER NOT NULL DEFAULT 1, note TEXT NOT NULL DEFAULT '', actor_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_vehicle_status_active ON vehicle_status(vehicle_id,active);
CREATE TABLE service_records (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id), service_type TEXT NOT NULL CHECK(service_type IN ('polish','body','repair','other')), status TEXT NOT NULL CHECK(status IN ('requested','in_progress','complete','cancelled')), spot_id TEXT REFERENCES parking_spots(id), note TEXT NOT NULL DEFAULT '', started_at TEXT, completed_at TEXT, actor_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_service_vehicle ON service_records(vehicle_id,created_at DESC);
CREATE TABLE vehicle_files (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id), object_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL CHECK(size_bytes >= 0), uploaded_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_files_vehicle ON vehicle_files(vehicle_id,created_at DESC);
CREATE TABLE push_subscriptions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), endpoint TEXT NOT NULL UNIQUE, p256dh TEXT NOT NULL, auth TEXT NOT NULL, failure_count INTEGER NOT NULL DEFAULT 0, last_success_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notification_preferences (user_id TEXT PRIMARY KEY REFERENCES users(id), scope TEXT NOT NULL DEFAULT 'important' CHECK(scope IN ('assigned','zones','important','all','off')), zone_ids TEXT NOT NULL DEFAULT '[]', quiet_hours_start TEXT, quiet_hours_end TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor_user_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, details_json TEXT NOT NULL DEFAULT '{}', success INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type,entity_id,created_at DESC); CREATE INDEX idx_audit_actor ON audit_logs(actor_user_id,created_at DESC);
CREATE TABLE notification_events (id TEXT PRIMARY KEY, event_type TEXT NOT NULL, vehicle_id TEXT REFERENCES vehicles(id), payload_json TEXT NOT NULL, delivery_status TEXT NOT NULL DEFAULT 'pending' CHECK(delivery_status IN ('pending','sent','partial','failed')), attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_notification_pending ON notification_events(delivery_status,created_at);

INSERT INTO parking_zones(id,name,short_name,zone_type,sort_order) VALUES ('pillar11','11번 기둥','11번','parking',1),('b3','지하 3층','B3','parking',2),('b5','지하 5층','B5','parking',3),('roof','옥상','옥상','parking',4),('tower','새싹타워','타워','parking',5),('auto13','오토플렉스 13층','13F','parking',6),('polish','광택 작업장','광택','service',7),('body','판금 작업장','판금','service',8),('repair','정비 작업장','수리','service',9);

INSERT INTO parking_spots(id,zone_id,label) SELECT 'pillar11-'||value,'pillar11',char(65+((value-1)%6))||CAST(((value-1)/6)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'b3-'||value,'b3',char(65+((value-1)%4))||CAST(((value-1)/4)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'b5-'||value,'b5',char(65+((value-1)%4))||CAST(((value-1)/4)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10,11,12]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'roof-'||value,'roof',char(65+((value-1)%4))||CAST(((value-1)/4)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'tower-'||value,'tower',char(65+((value-1)%5))||CAST(((value-1)/5)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'auto13-'||value,'auto13',char(65+((value-1)%4))||CAST(((value-1)/4)+1 AS INTEGER) FROM json_each('[1,2,3,4,5,6,7,8,9,10,11,12]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'polish-'||value,'polish',char(64+value)||'1' FROM json_each('[1,2,3,4]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'body-'||value,'body',char(64+value)||'1' FROM json_each('[1,2,3,4]');
INSERT INTO parking_spots(id,zone_id,label) SELECT 'repair-'||value,'repair',char(64+value)||'1' FROM json_each('[1,2,3,4]');
PRAGMA optimize;
