const SHEETS_SCOPE='https://www.googleapis.com/auth/spreadsheets';
const TOKEN_URL='https://oauth2.googleapis.com/token';
const tokenCache=new Map();

const base64Url=input=>btoa(input).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const bytesToBase64Url=bytes=>{let value='';for(let index=0;index<bytes.length;index+=0x8000)value+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return base64Url(value);};
const utf8Base64Url=value=>bytesToBase64Url(new TextEncoder().encode(value));
const sheetRange=(title,range)=>`'${String(title).replace(/'/g,"''")}'!${range}`;
export const normalizeSheetPlate=value=>String(value||'').replace(/\s+/g,'').trim();

function googleConfig(env){const clientEmail=String(env.GOOGLE_CLIENT_EMAIL||'').trim(),privateKey=String(env.GOOGLE_PRIVATE_KEY||'').replace(/\\n/g,'\n').trim(),sheetId=String(env.GOOGLE_SHEET_ID||'').trim();if(!clientEmail||!privateKey||!sheetId)throw new Error('Google Sheets 환경변수가 설정되지 않았습니다.');return{clientEmail,privateKey,sheetId};}
async function importPrivateKey(pem){const base64=pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,''),binary=atob(base64),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return crypto.subtle.importKey('pkcs8',bytes,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);}
async function accessToken(env){const {clientEmail,privateKey}=googleConfig(env),cached=tokenCache.get(clientEmail),now=Math.floor(Date.now()/1000);if(cached&&cached.expiresAt>now+60)return cached.token;const header=utf8Base64Url(JSON.stringify({alg:'RS256',typ:'JWT'})),claims=utf8Base64Url(JSON.stringify({iss:clientEmail,scope:SHEETS_SCOPE,aud:TOKEN_URL,iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,key=await importPrivateKey(privateKey),signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned)),assertion=`${unsigned}.${bytesToBase64Url(new Uint8Array(signature))}`,response=await fetch(TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})}),data=await response.json();if(!response.ok||!data.access_token)throw new Error(`Google 서비스계정 인증에 실패했습니다${data.error_description?`: ${String(data.error_description).slice(0,160)}`:''}.`);tokenCache.set(clientEmail,{token:data.access_token,expiresAt:now+Number(data.expires_in||3600)});return data.access_token;}
async function googleFetch(env,path,options={}){const token=await accessToken(env),response=await fetch(`https://sheets.googleapis.com/v4/${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Google Sheets 요청에 실패했습니다${data?.error?.message?`: ${String(data.error.message).slice(0,200)}`:''}.`);return data;}

export async function listGoogleSheetTabs(env){const {sheetId}=googleConfig(env),data=await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}?fields=spreadsheetId,sheets.properties(sheetId,title,index)`);return(data.sheets||[]).map(sheet=>({id:sheet.properties.sheetId,title:sheet.properties.title,index:sheet.properties.index})).sort((a,b)=>a.index-b.index);}

function recordValues(record){return[
  normalizeSheetPlate(record.plate),String(record.model||''),'',String(record.model_year||''),String(record.color||''),'','',String(record.options||''),String(record.customer_type||''),false,false,false,'','','','','',String(record.memo||record.manager||''),
];}

async function writeValues(env,sheetId,tab,row,values,startColumn){const range=sheetRange(tab,`${startColumn}${row}:S${row}`);await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,{method:'PUT',body:JSON.stringify({range,majorDimension:'ROWS',values:[values]})});}
async function copyTemplateRow(env,sheetId,numericSheetId,sourceRow,targetRow){if(targetRow<=1)return;await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}:batchUpdate`,{method:'POST',body:JSON.stringify({requests:['PASTE_FORMAT','PASTE_DATA_VALIDATION'].map(pasteType=>({copyPaste:{source:{sheetId:numericSheetId,startRowIndex:sourceRow-1,endRowIndex:sourceRow,startColumnIndex:0,endColumnIndex:19},destination:{sheetId:numericSheetId,startRowIndex:targetRow-1,endRowIndex:targetRow,startColumnIndex:0,endColumnIndex:19},pasteType,pasteOrientation:'NORMAL'}}))})});}

export async function syncGoogleSheetRecords(env,tabTitle,records){const {sheetId}=googleConfig(env),tabs=await listGoogleSheetTabs(env),tab=tabs.find(item=>item.title===tabTitle);if(!tab)throw new Error('선택한 스프레드시트 탭을 찾을 수 없습니다.');const range=sheetRange(tab.title,'A:S'),data=await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(range)}?majorDimension=ROWS`),rows=Array.isArray(data.values)?data.values:[],plateRows=new Map();let lastVehicleRow=1,lastSequence=0;rows.forEach((row,index)=>{const rowNumber=index+1,plate=normalizeSheetPlate(row[1]);if(plate){plateRows.set(plate,rowNumber);lastVehicleRow=Math.max(lastVehicleRow,rowNumber);}const sequence=Number(row[0]);if(Number.isFinite(sequence))lastSequence=Math.max(lastSequence,sequence);});let updated=0,inserted=0,failed=0,lastAction=null,lastRow=null;for(const record of records){try{const plate=normalizeSheetPlate(record.plate);if(!plate)throw new Error('차량번호가 없습니다.');const existingRow=plateRows.get(plate),values=recordValues(record);if(existingRow){await writeValues(env,sheetId,tab.title,existingRow,values,'B');updated+=1;lastAction='updated';lastRow=existingRow;}else{const targetRow=lastVehicleRow+1,sourceRow=Math.max(1,lastVehicleRow);await copyTemplateRow(env,sheetId,tab.id,sourceRow,targetRow);lastSequence+=1;await writeValues(env,sheetId,tab.title,targetRow,[lastSequence,...values],'A');plateRows.set(plate,targetRow);lastVehicleRow=targetRow;inserted+=1;lastAction='inserted';lastRow=targetRow;}}catch{failed+=1;}}return{success:failed===0,updated,inserted,failed,action:lastAction,row:lastRow};}

export async function testGoogleSheets(env){const tabs=await listGoogleSheetTabs(env);return{success:true,spreadsheetId:googleConfig(env).sheetId,tabs:tabs.length};}
