const SHEETS_SCOPE='https://www.googleapis.com/auth/spreadsheets';
const TOKEN_URL='https://oauth2.googleapis.com/token';
const tokenCache=new Map();

const base64Url=input=>btoa(input).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const bytesToBase64Url=bytes=>{let value='';for(let index=0;index<bytes.length;index+=0x8000)value+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return base64Url(value);};
const utf8Base64Url=value=>bytesToBase64Url(new TextEncoder().encode(value));
const sheetRange=(title,range)=>`'${String(title).replace(/'/g,"''")}'!${range}`;
export const normalizeSheetPlate=value=>String(value||'').replace(/\s+/g,'').trim();
export const normalizeSheetDate=value=>{const match=String(value||'').match(/(\d{4})[-./](\d{1,2})[-./](\d{1,2})/);if(!match)return'';const timestamp=Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]));return Number.isNaN(timestamp)?'':timestamp/86400000+25569;};
export const normalizeSheetDepartureDate=value=>{const source=String(value||''),date=source.match(/(\d{4})\s*[-./년]\s*(\d{1,2})\s*[-./월]\s*(\d{1,2})/);if(!date)return'';const koreanTime=source.match(/(오전|오후)\s*(\d{1,2})\s*(?::|시)\s*(\d{1,2})?\s*분?/),clockTime=source.match(/(?:^|\s)([01]?\d|2[0-3]):([0-5]\d)(?:\s|$|출발)/);let hours,minutes;if(koreanTime){hours=Number(koreanTime[2])%12+(koreanTime[1]==='오후'?12:0);minutes=Number(koreanTime[3]||0);}else if(clockTime){hours=Number(clockTime[1]);minutes=Number(clockTime[2]);}const formattedDate=`${date[1]}-${date[2].padStart(2,'0')}-${date[3].padStart(2,'0')}`;return hours===undefined?formattedDate:`${formattedDate} ${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}`;};
export const normalizePolishingVendor=value=>String(value||'').match(/^\[광택\]\s*(스타|신화)/)?.[1]||'';
export const normalizeSheetMileage=value=>{const digits=String(value||'').replace(/[^0-9]/g,'');return digits?Number(digits):'';};

function googleConfig(env){const clientEmail=String(env.GOOGLE_CLIENT_EMAIL||'').trim(),privateKey=String(env.GOOGLE_PRIVATE_KEY||'').replace(/\\n/g,'\n').trim(),sheetId=String(env.GOOGLE_SHEET_ID||'').trim();if(!clientEmail||!privateKey||!sheetId)throw new Error('Google Sheets 환경변수가 설정되지 않았습니다.');return{clientEmail,privateKey,sheetId};}
async function importPrivateKey(pem){const base64=pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,''),binary=atob(base64),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return crypto.subtle.importKey('pkcs8',bytes,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);}
async function accessToken(env){const {clientEmail,privateKey}=googleConfig(env),cached=tokenCache.get(clientEmail),now=Math.floor(Date.now()/1000);if(cached&&cached.expiresAt>now+60)return cached.token;const header=utf8Base64Url(JSON.stringify({alg:'RS256',typ:'JWT'})),claims=utf8Base64Url(JSON.stringify({iss:clientEmail,scope:SHEETS_SCOPE,aud:TOKEN_URL,iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,key=await importPrivateKey(privateKey),signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned)),assertion=`${unsigned}.${bytesToBase64Url(new Uint8Array(signature))}`,response=await fetch(TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})}),data=await response.json();if(!response.ok||!data.access_token)throw new Error(`Google 서비스계정 인증에 실패했습니다${data.error_description?`: ${String(data.error_description).slice(0,160)}`:''}.`);tokenCache.set(clientEmail,{token:data.access_token,expiresAt:now+Number(data.expires_in||3600)});return data.access_token;}
async function googleFetch(env,path,options={}){const token=await accessToken(env),response=await fetch(`https://sheets.googleapis.com/v4/${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Google Sheets 요청에 실패했습니다${data?.error?.message?`: ${String(data.error.message).slice(0,200)}`:''}.`);return data;}

export async function listGoogleSheetTabs(env){const {sheetId}=googleConfig(env),data=await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}?fields=spreadsheetId,sheets.properties(sheetId,title,index)`);return(data.sheets||[]).map(sheet=>({id:sheet.properties.sheetId,title:sheet.properties.title,index:sheet.properties.index})).sort((a,b)=>a.index-b.index);}

function recordValues(record){return[
  normalizeSheetPlate(record.plate),String(record.model||''),'',String(record.model_year||''),String(record.color||''),normalizeSheetMileage(record.mileage),String(record.manager||''),String(record.options||''),String(record.customer_type||''),normalizeSheetDate(record.checked_out_at||record.checked_in_at||record.record_date),normalizeSheetDate(record.performance_service_date),normalizePolishingVendor(record.polishing_note),false,'','','','','',String(record.origin||''),normalizeSheetDepartureDate(record.departure_time),
];}

const sheetSequence=(record,fallback)=>{if(normalizeSheetPlate(record.plate)==='59다3609')return 0;const sequence=Number(record.board_order);return Number.isInteger(sequence)&&sequence>0?sequence:fallback;};

async function writeRecordBatch(env,sheetId,tab,items){const data=items.flatMap(({row,sequence,values,record})=>[{range:sheetRange(tab,`A${row}:U${row}`),majorDimension:'ROWS',values:[[sequence,...values]]},{range:sheetRange(tab,`X${row}:Z${row}`),majorDimension:'ROWS',values:[[String(record.price||''),String(record.account||''),Boolean(record.checked_out_at)]]}]);await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}/values:batchUpdate`,{method:'POST',body:JSON.stringify({valueInputOption:'USER_ENTERED',data})});}
async function ensureSyncHeaders(env,sheetId,tab,headers){const writes=[];if(String(headers[10]||'').trim()!=='입,출고일')writes.push({range:sheetRange(tab,'K1'),values:[['입,출고일']]});if(String(headers[19]||'').trim()!=='탁송출발지'||String(headers[20]||'').trim()!=='탁송출발시간')writes.push({range:sheetRange(tab,'T1:U1'),values:[['탁송출발지','탁송출발시간']]});if(String(headers[23]||'').trim()!=='차대금'||String(headers[24]||'').trim()!=='입금계좌'||String(headers[25]||'').trim()!=='판매됨')writes.push({range:sheetRange(tab,'X1:Z1'),values:[['차대금','입금계좌','판매됨']]});for(const write of writes)await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(write.range)}?valueInputOption=USER_ENTERED`,{method:'PUT',body:JSON.stringify({range:write.range,majorDimension:'ROWS',values:write.values})});}
async function copyTemplateRow(env,sheetId,numericSheetId,sourceRow,targetRow){if(targetRow<=1)return;await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}:batchUpdate`,{method:'POST',body:JSON.stringify({requests:['PASTE_FORMAT','PASTE_DATA_VALIDATION'].map(pasteType=>({copyPaste:{source:{sheetId:numericSheetId,startRowIndex:sourceRow-1,endRowIndex:sourceRow,startColumnIndex:0,endColumnIndex:26},destination:{sheetId:numericSheetId,startRowIndex:targetRow-1,endRowIndex:targetRow,startColumnIndex:0,endColumnIndex:26},pasteType,pasteOrientation:'NORMAL'}}))})});}

export async function syncGoogleSheetRecords(env,tabTitle,records){const {sheetId}=googleConfig(env),tabs=await listGoogleSheetTabs(env),tab=tabs.find(item=>item.title===tabTitle);if(!tab)throw new Error('선택한 스프레드시트 탭을 찾을 수 없습니다.');const range=sheetRange(tab.title,'A:Z'),data=await googleFetch(env,`spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(range)}?majorDimension=ROWS`),rows=Array.isArray(data.values)?data.values:[],plateRows=new Map();await ensureSyncHeaders(env,sheetId,tab.title,rows[0]||[]);let lastVehicleRow=1,lastSequence=0;rows.forEach((row,index)=>{const rowNumber=index+1,plate=normalizeSheetPlate(row[1]),sequence=Number(row[0]);if(plate){plateRows.set(plate,{row:rowNumber,sequence:Number.isInteger(sequence)&&sequence>0?sequence:null});lastVehicleRow=Math.max(lastVehicleRow,rowNumber);}if(Number.isFinite(sequence))lastSequence=Math.max(lastSequence,sequence);});let updated=0,inserted=0,failed=0,lastAction=null,lastRow=null;const pending=[];for(const record of records){try{const plate=normalizeSheetPlate(record.plate);if(!plate)throw new Error('차량번호가 없습니다.');const existing=plateRows.get(plate),values=recordValues(record);if(existing){const sequence=sheetSequence(record,existing.sequence||lastSequence+1);lastSequence=Math.max(lastSequence,sequence);pending.push({action:'updated',row:existing.row,sequence,values,record});}else{const targetRow=lastVehicleRow+1,sourceRow=Math.max(1,lastVehicleRow);await copyTemplateRow(env,sheetId,tab.id,sourceRow,targetRow);const sequence=sheetSequence(record,lastSequence+1);lastSequence=Math.max(lastSequence,sequence);pending.push({action:'inserted',row:targetRow,sequence,values,record});plateRows.set(plate,{row:targetRow,sequence});lastVehicleRow=targetRow;}}catch{failed+=1;}}for(let index=0;index<pending.length;index+=50){const batch=pending.slice(index,index+50);try{await writeRecordBatch(env,sheetId,tab.title,batch);for(const item of batch){if(item.action==='updated')updated+=1;else inserted+=1;lastAction=item.action;lastRow=item.row;}}catch{failed+=batch.length;}}return{success:failed===0,updated,inserted,failed,action:lastAction,row:lastRow};}

export async function testGoogleSheets(env){const tabs=await listGoogleSheetTabs(env);return{success:true,spreadsheetId:googleConfig(env).sheetId,tabs:tabs.length};}
