import {canWrite,normalizePlate,STATUSES,validateVehicle} from '../../src/validation.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const id=()=>crypto.randomUUID();
async function body(request){try{return await request.json();}catch{return null;}}
async function actor(request,env){const email=request.headers.get('CF-Access-Authenticated-User-Email')||(env.ALLOW_DEMO_AUTH==='true'?request.headers.get('X-Demo-User'):null);if(!email)return null;return await env.DB.prepare('SELECT id,email,name,role FROM users WHERE email=? AND active=1').bind(email.toLowerCase()).first();}
async function requireUser(request,env,write=false){const user=await actor(request,env);if(!user)return{error:json({message:'로그인이 필요합니다.'},401)};if(write&&!canWrite(user.role))return{error:json({message:'이 작업을 수행할 권한이 없습니다.'},403)};return{user};}
const vehicleSelect=`SELECT v.*,s.label spot_label,z.id zone_id,z.name zone_name,z.short_name zone_short,z.zone_type FROM vehicles v LEFT JOIN parking_spots s ON s.id=v.current_spot_id LEFT JOIN parking_zones z ON z.id=s.zone_id`;
async function audit(db,user,action,type,entity,details={},success=1){await db.prepare('INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,details_json,success) VALUES(?,?,?,?,?,?,?)').bind(id(),user?.id||null,action,type,entity,JSON.stringify(details),success).run();}
async function event(db,type,vehicleId,payload){await db.prepare('INSERT INTO notification_events(id,event_type,vehicle_id,payload_json) VALUES(?,?,?,?)').bind(id(),type,vehicleId,JSON.stringify(payload)).run();}
async function listSpots(db){return (await db.prepare(`SELECT s.id,s.zone_id,s.label,s.version,z.name zone,z.short_name zone_short,z.zone_type,v.id vehicle_id,v.plate,v.model,v.color,v.memo,v.version vehicle_version,v.updated_at,COALESCE((SELECT json_group_array(status_type) FROM vehicle_status vs WHERE vs.vehicle_id=v.id AND vs.active=1),'[]') alerts FROM parking_spots s JOIN parking_zones z ON z.id=s.zone_id LEFT JOIN vehicles v ON v.id=s.current_vehicle_id WHERE s.active=1 AND z.active=1 ORDER BY z.sort_order,s.label`).all()).results;}
async function dashboard(db){const spots=await listSpots(db);const parking=spots.filter(s=>s.zone_type==='parking');return{stats:{total:parking.length,occupied:parking.filter(s=>s.vehicle_id).length,empty:parking.filter(s=>!s.vehicle_id).length,alerts:spots.filter(s=>s.vehicle_id&&JSON.parse(s.alerts).length).length},spots};}

export async function onRequest(context){const {request,env,params}=context;if(!env.DB)return json({message:'D1 데이터베이스 연결이 필요합니다.'},503);const auth=await requireUser(request,env,request.method!=='GET');if(auth.error)return auth.error;const user=auth.user,url=new URL(request.url),parts=(params.path||[]).filter(Boolean),method=request.method;
 try{
  if(method==='GET'&&parts[0]==='dashboard')return json(await dashboard(env.DB));
  if(method==='GET'&&parts[0]==='zones')return json({zones:(await env.DB.prepare('SELECT * FROM parking_zones WHERE active=1 ORDER BY sort_order').all()).results});
  if(method==='GET'&&parts[0]==='spots')return json({spots:await listSpots(env.DB)});
  if(method==='GET'&&parts[0]==='vehicles'&&!parts[1]){const q=url.searchParams.get('q')||'',history=url.searchParams.get('history')==='true';const rows=await env.DB.prepare(`${vehicleSelect} WHERE (v.plate LIKE ? OR v.model LIKE ? OR v.color LIKE ?) ${history?'':'AND v.checked_out_at IS NULL'} ORDER BY v.updated_at DESC LIMIT 200`).bind(`%${q}%`,`%${q}%`,`%${q}%`).all();return json({vehicles:rows.results});}
  if(method==='GET'&&parts[0]==='vehicles'&&parts[1]&&parts[2]==='history'){const rows=await env.DB.prepare(`SELECT m.*,fs.label from_label,fz.name from_zone,ts.label to_label,tz.name to_zone,u.name actor_name FROM parking_movements m LEFT JOIN parking_spots fs ON fs.id=m.from_spot_id LEFT JOIN parking_zones fz ON fz.id=fs.zone_id LEFT JOIN parking_spots ts ON ts.id=m.to_spot_id LEFT JOIN parking_zones tz ON tz.id=ts.zone_id JOIN users u ON u.id=m.actor_user_id WHERE m.vehicle_id=? ORDER BY m.created_at DESC`).bind(parts[1]).all();return json({history:rows.results});}
  if(method==='GET'&&parts[0]==='vehicles'&&parts[1]){const vehicle=await env.DB.prepare(`${vehicleSelect} WHERE v.id=?`).bind(parts[1]).first();if(!vehicle)return json({message:'차량을 찾을 수 없습니다.'},404);const [statuses,services,files]=await Promise.all([env.DB.prepare('SELECT * FROM vehicle_status WHERE vehicle_id=? ORDER BY created_at DESC').bind(parts[1]).all(),env.DB.prepare('SELECT * FROM service_records WHERE vehicle_id=? ORDER BY created_at DESC').bind(parts[1]).all(),env.DB.prepare('SELECT id,filename,mime_type,size_bytes,created_at FROM vehicle_files WHERE vehicle_id=? ORDER BY created_at DESC').bind(parts[1]).all()]);return json({vehicle,statuses:statuses.results,services:services.results,files:files.results});}
  if(method==='POST'&&parts.join('/')==='vehicles/check-in'){const input=await body(request),valid=validateVehicle(input);if(!valid.ok)return json({message:valid.message},400);const spot=await env.DB.prepare('SELECT id,current_vehicle_id,version FROM parking_spots WHERE id=? AND active=1').bind(input.spotId).first();if(!spot)return json({message:'주차면을 찾을 수 없습니다.'},404);if(spot.current_vehicle_id)return json({message:'이미 사용 중인 주차면입니다.'},409);if(await env.DB.prepare('SELECT id FROM vehicles WHERE plate=? AND checked_out_at IS NULL').bind(valid.value.plate).first())return json({message:'현재 주차 중인 차량번호입니다.'},409);const vehicleId=id(),movementId=id(),auditId=id(),eventId=id();const results=await env.DB.batch([env.DB.prepare('INSERT INTO vehicles(id,plate,model,color,memo,current_spot_id,checked_in_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(vehicleId,valid.value.plate,valid.value.model,valid.value.color,valid.value.memo,spot.id),env.DB.prepare('UPDATE parking_spots SET current_vehicle_id=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND current_vehicle_id IS NULL AND version=?').bind(vehicleId,spot.id,spot.version),env.DB.prepare("INSERT INTO parking_movements(id,vehicle_id,movement_type,to_spot_id,actor_user_id) VALUES(?,?,'check_in',?,?)").bind(movementId,vehicleId,spot.id,user.id),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,details_json) VALUES(?,?,'check_in','vehicle',?,?)").bind(auditId,user.id,vehicleId,JSON.stringify({spotId:spot.id})),env.DB.prepare("INSERT INTO notification_events(id,event_type,vehicle_id,payload_json) VALUES(?,? ,?,?)").bind(eventId,'check_in',vehicleId,JSON.stringify({plate:valid.value.plate,spotId:spot.id}))]);if(!results[1].meta.changes)return json({message:'다른 사용자가 먼저 이 주차면을 사용했습니다. 새로고침 후 다시 시도해 주세요.'},409);return json({id:vehicleId,message:'입차가 등록되었습니다.'},201);}
  if(method==='PATCH'&&parts[0]==='vehicles'&&parts[1]&&!parts[2]){const input=await body(request),valid=validateVehicle(input);if(!valid.ok)return json({message:valid.message},400);const current=await env.DB.prepare('SELECT version FROM vehicles WHERE id=? AND checked_out_at IS NULL').bind(parts[1]).first();if(!current)return json({message:'현재 주차 중인 차량을 찾을 수 없습니다.'},404);if(Number(input.version)!==current.version)return json({message:'다른 사용자가 먼저 수정했습니다. 새로고침 후 다시 시도해 주세요.'},409);try{await env.DB.prepare('UPDATE vehicles SET plate=?,model=?,color=?,memo=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=?').bind(valid.value.plate,valid.value.model,valid.value.color,valid.value.memo,parts[1],current.version).run();}catch{return json({message:'현재 주차 중인 동일 차량번호가 있습니다.'},409);}await audit(env.DB,user,'update','vehicle',parts[1]);return json({message:'차량 정보가 저장되었습니다.'});}
  if(method==='POST'&&parts[0]==='vehicles'&&parts[1]&&parts[2]==='move'){const input=await body(request),vehicle=await env.DB.prepare('SELECT id,plate,current_spot_id,version FROM vehicles WHERE id=? AND checked_out_at IS NULL').bind(parts[1]).first(),target=await env.DB.prepare('SELECT id,current_vehicle_id,version FROM parking_spots WHERE id=? AND active=1').bind(input?.spotId).first();if(!vehicle)return json({message:'현재 주차 중인 차량을 찾을 수 없습니다.'},404);if(!target)return json({message:'이동할 주차면을 찾을 수 없습니다.'},404);if(target.current_vehicle_id)return json({message:'이미 사용 중인 주차면입니다.'},409);if(Number(input.version)!==vehicle.version)return json({message:'차량 위치가 이미 변경되었습니다. 새로고침해 주세요.'},409);const movementType=input.serviceType?'service':'move',movementId=id(),auditId=id(),eventId=id();const batch=[env.DB.prepare('UPDATE parking_spots SET current_vehicle_id=NULL,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND current_vehicle_id=?').bind(vehicle.current_spot_id,vehicle.id),env.DB.prepare('UPDATE parking_spots SET current_vehicle_id=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND current_vehicle_id IS NULL AND version=?').bind(vehicle.id,target.id,target.version),env.DB.prepare('UPDATE vehicles SET current_spot_id=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=?').bind(target.id,vehicle.id,vehicle.version),env.DB.prepare('INSERT INTO parking_movements(id,vehicle_id,movement_type,from_spot_id,to_spot_id,actor_user_id) VALUES(?,?,?,?,?,?)').bind(movementId,vehicle.id,movementType,vehicle.current_spot_id,target.id,user.id),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,details_json) VALUES(?,?,'move','vehicle',?,?)").bind(auditId,user.id,vehicle.id,JSON.stringify({from:vehicle.current_spot_id,to:target.id})),env.DB.prepare('INSERT INTO notification_events(id,event_type,vehicle_id,payload_json) VALUES(?,?,?,?)').bind(eventId,movementType,vehicle.id,JSON.stringify({plate:vehicle.plate,from:vehicle.current_spot_id,to:target.id}))];if(input.serviceType)batch.push(env.DB.prepare("INSERT INTO service_records(id,vehicle_id,service_type,status,spot_id,actor_user_id,started_at) VALUES(?,?,?,'in_progress',?,?,CURRENT_TIMESTAMP)").bind(id(),vehicle.id,input.serviceType,target.id,user.id));const results=await env.DB.batch(batch);if(!results[1].meta.changes||!results[2].meta.changes)return json({message:'동시에 위치가 변경되었습니다. 새로고침 후 다시 시도해 주세요.'},409);return json({message:'차량 위치가 변경되었습니다. 알림은 별도로 처리됩니다.'});}
  if(method==='POST'&&parts[0]==='vehicles'&&parts[1]&&parts[2]==='check-out'){const vehicle=await env.DB.prepare('SELECT * FROM vehicles WHERE id=? AND checked_out_at IS NULL').bind(parts[1]).first();if(!vehicle)return json({message:'현재 주차 중인 차량을 찾을 수 없습니다.'},404);const results=await env.DB.batch([env.DB.prepare('UPDATE parking_spots SET current_vehicle_id=NULL,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND current_vehicle_id=?').bind(vehicle.current_spot_id,vehicle.id),env.DB.prepare('UPDATE vehicles SET current_spot_id=NULL,checked_out_at=CURRENT_TIMESTAMP,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=?').bind(vehicle.id,vehicle.version),env.DB.prepare("INSERT INTO parking_movements(id,vehicle_id,movement_type,from_spot_id,actor_user_id) VALUES(?,?,'check_out',?,?)").bind(id(),vehicle.id,vehicle.current_spot_id,user.id),env.DB.prepare("INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,details_json) VALUES(?,?,'check_out','vehicle',?,'{}')").bind(id(),user.id,vehicle.id),env.DB.prepare('INSERT INTO notification_events(id,event_type,vehicle_id,payload_json) VALUES(?,?,?,?)').bind(id(),'check_out',vehicle.id,JSON.stringify({plate:vehicle.plate,from:vehicle.current_spot_id}))]);if(!results[1].meta.changes)return json({message:'차량이 이미 변경되었습니다. 새로고침해 주세요.'},409);return json({message:'출차 처리되었습니다.'});}
  if(method==='POST'&&parts[0]==='vehicles'&&parts[1]&&parts[2]==='status'){const input=await body(request);if(!STATUSES.includes(input?.statusType))return json({message:'지원하지 않는 차량 상태입니다.'},400);const statusId=id();await env.DB.prepare('INSERT INTO vehicle_status(id,vehicle_id,status_type,active,note,actor_user_id) VALUES(?,?,?,?,?,?)').bind(statusId,parts[1],input.statusType,input.active===false?0:1,String(input.note||'').slice(0,500),user.id).run();await audit(env.DB,user,'status','vehicle',parts[1],input);if(['battery','engine'].includes(input.statusType)&&input.active!==false)await event(env.DB,'important_status',parts[1],{statusType:input.statusType});return json({id:statusId,message:'차량 상태가 저장되었습니다.'},201);}
  if(method==='GET'&&parts.join('/')==='push/public-key')return json({publicKey:env.VAPID_PUBLIC_KEY||null});
  if(method==='POST'&&parts.join('/')==='push/subscribe'){const input=await body(request);if(!input?.endpoint||!input?.keys?.p256dh||!input?.keys?.auth)return json({message:'올바른 푸시 구독 정보가 아닙니다.'},400);await env.DB.prepare(`INSERT INTO push_subscriptions(id,user_id,endpoint,p256dh,auth) VALUES(?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,updated_at=CURRENT_TIMESTAMP`).bind(id(),user.id,input.endpoint,input.keys.p256dh,input.keys.auth).run();return json({message:'알림이 활성화되었습니다.'},201);}
  if(method==='DELETE'&&parts.join('/')==='push/subscribe'){const input=await body(request);await env.DB.prepare('DELETE FROM push_subscriptions WHERE user_id=? AND endpoint=?').bind(user.id,input?.endpoint||'').run();return json({message:'알림 구독이 해제되었습니다.'});}
  if(method==='PATCH'&&parts[0]==='notification-preferences'){const input=await body(request),allowed=['assigned','zones','important','all','off'];if(!allowed.includes(input?.scope))return json({message:'알림 범위를 확인해 주세요.'},400);await env.DB.prepare(`INSERT INTO notification_preferences(user_id,scope,zone_ids,quiet_hours_start,quiet_hours_end) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET scope=excluded.scope,zone_ids=excluded.zone_ids,quiet_hours_start=excluded.quiet_hours_start,quiet_hours_end=excluded.quiet_hours_end,updated_at=CURRENT_TIMESTAMP`).bind(user.id,input.scope,JSON.stringify(input.zoneIds||[]),input.quietStart||null,input.quietEnd||null).run();return json({message:'알림 설정이 저장되었습니다.'});}
  return json({message:'요청한 API를 찾을 수 없습니다.'},404);
 }catch(error){console.error(error);return json({message:'데이터베이스 처리 중 오류가 발생했습니다.'},500);}
}
