import './style.css';
import {makeInitialSpots,STATUS,zones} from './data.js';
import {normalizePlate,validateVehicle} from './validation.js';
import {parkingLayouts} from './parking-layouts.js';
import {renderParkingMap} from './parking-map.js';

const app=document.querySelector('#app');
const state={spots:[],unassigned:[],query:'',zone:'all',filter:'all',managerFilter:'all',expandedLayouts:new Set(),selected:null,mode:'detail',notice:'',error:'',loading:true,backend:false,saving:false};
const used=s=>Boolean(s.plate),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normalizeVehicleColor=value=>['회색','은색'].includes(String(value||'').trim())?'쥐색':String(value||'').trim();
async function api(path,options={}){const response=await fetch(`/api/${path}`,{headers:{'Content-Type':'application/json'},...options});const data=await response.json().catch(()=>({message:'서버 응답을 읽을 수 없습니다.'}));if(!response.ok)throw new Error(data.message||'요청을 처리하지 못했습니다.');return data;}
async function searchVehicleHistory(searchTerm){const query=normalizePlate(searchTerm),digits=query.replace(/\D/g,'');if(!query)return[];const exactLastFour=/^\d{4}$/.test(query);const data=await api(`vehicles?q=${encodeURIComponent(query)}&history=true`);return(data.vehicles||[]).filter(vehicle=>{const plate=normalizePlate(vehicle.plate);return exactLastFour?plate.replace(/\D/g,'').slice(-4)===digits:plate.includes(query);});}
function mapSpot(s){return{id:s.id,zoneId:s.zone_id,zone:s.zone,zoneShort:s.zone_short,label:s.label,plate:s.plate||'',model:s.model||'',modelYear:s.model_year||'',color:normalizeVehicleColor(s.color),options:s.options||'',manager:s.manager||'',memo:s.memo||'',checkedInAt:s.checked_in_at||'',alerts:Array.isArray(s.alerts)?s.alerts:JSON.parse(s.alerts||'[]'),updatedAt:s.updated_at||'',vehicleId:s.vehicle_id||null,version:s.version||0,vehicleVersion:s.vehicle_version||0};}
const mapUnassigned=v=>({id:`queue-${v.vehicle_id}`,vehicleId:v.vehicle_id,vehicleVersion:v.vehicle_version,plate:v.plate,model:v.model||'',modelYear:v.model_year||'',color:normalizeVehicleColor(v.color),options:v.options||'',manager:v.manager||'',memo:v.memo||'',checkedInAt:v.checked_in_at||'',alerts:[],zone:'차량 현황판',label:'주차 미배정',isUnassigned:true});
async function load(){state.loading=true;render();try{const data=await api('dashboard');state.unassigned=(data.unassigned||[]).map(mapUnassigned);state.spots=[...data.spots.map(mapSpot),...state.unassigned];state.backend=true;state.error='';}catch{state.spots=makeInitialSpots();state.unassigned=[];state.backend=false;state.error='운영 데이터베이스가 아직 연결되지 않아 읽기 전용 데모 데이터를 표시합니다.';}finally{state.loading=false;render();}}
async function refresh(message=''){try{const data=await api('dashboard');state.unassigned=(data.unassigned||[]).map(mapUnassigned);state.spots=[...data.spots.map(mapSpot),...state.unassigned];state.backend=true;state.notice=message;}catch(e){state.error=e.message;}finally{state.saving=false;state.selected=null;render();if(message)setTimeout(()=>{state.notice='';render();},2200);}}
function stats(){const p=state.spots.filter(s=>zones.find(z=>z.id===s.zoneId)?.type==='parking'),n=p.filter(used).length;return{total:p.length,occupied:n,empty:p.length-n,alerts:state.spots.filter(s=>used(s)&&s.alerts.length).length};}
function visible(){const q=state.query.trim().toLowerCase();return state.spots.filter(s=>{const zone=zones.find(z=>z.id===s.zoneId);if(zone?.type==='service'&&!used(s))return false;return(state.zone==='all'||s.zoneId===state.zone)&&(state.filter==='all'||(state.filter==='occupied'&&used(s))||(state.filter==='empty'&&!used(s))||(state.filter==='alert'&&s.alerts.length)||(state.filter==='service'&&zone?.type==='service'))&&(!q||[s.plate,s.model,s.color,s.manager,s.label,s.zone,s.memo].some(v=>String(v).toLowerCase().includes(q)));});}
function highlightSearchZoneTabs(){const query=state.query.trim().toLowerCase(),matchedZones=new Set(query?state.spots.filter(s=>used(s)&&[s.plate,s.model,s.color,s.manager,s.label,s.zone].some(value=>String(value).toLowerCase().includes(query))).map(s=>s.zoneId):[]);document.querySelectorAll('.zone-tabs [data-zone]').forEach(button=>button.classList.toggle('search-match',button.dataset.zone!=='all'&&matchedZones.has(button.dataset.zone)));}
function renderParkingSearchResults(){highlightSearchZoneTabs();const toolbar=document.querySelector('.workspace .toolbar');if(!toolbar)return;toolbar.querySelector('.parking-search-results')?.remove();const query=state.query.trim().toLowerCase();if(!query)return;const matches=state.spots.filter(s=>used(s)&&[s.plate,s.model,s.color,s.manager,s.label,s.zone].some(value=>String(value).toLowerCase().includes(query)));const panel=document.createElement('div');panel.className='parking-search-results';panel.setAttribute('aria-live','polite');panel.innerHTML=matches.length?matches.map(s=>{const notes=s.alerts.map(id=>STATUS.find(item=>item.id===id)?.label).filter(Boolean).join(' · ')||'없음';return`<button type="button" data-search-spot="${esc(s.id)}" aria-label="${esc(s.plate)} 차량 상세 보기"><strong>${esc(s.plate)}</strong><span><small>주차구역</small>${esc(s.zone)} ${esc(s.label)}</span><span><small>차종</small>${esc(s.model)||'-'}</span><span><small>색상</small>${esc(normalizeVehicleColor(s.color))||'-'}</span><span><small>담당자</small>${esc(s.manager)||'-'}</span><span><small>입고날짜</small>${esc(String(s.checkedInAt||'').slice(0,10))||'-'}</span><span><small>특이사항</small>${esc(notes)}</span></button>`;}).join(''):'<p>일치하는 주차 차량이 없습니다.</p>';toolbar.append(panel);panel.querySelectorAll('[data-search-spot]').forEach(button=>button.onclick=()=>{const vehicle=state.spots.find(item=>item.id===button.dataset.searchSpot);state.query=vehicle?.plate||state.query;state.selected=button.dataset.searchSpot;state.mode='detail';render();});}
const metric=(l,v,en,t='')=>`<article class="metric ${t}"><span>${en}</span><div><strong>${v}</strong><small>${l}</small></div></article>`;
function spot(s){const alerts=s.alerts.map(id=>STATUS.find(x=>x.id===id)?.label).filter(Boolean);return`<button class="spot ${used(s)?'is-used':'is-empty'} ${alerts.length?'has-alert':''}" data-spot="${s.id}" aria-label="${s.zone} ${s.label} ${s.plate||'빈 자리'}"><span class="spot-label">${s.label}</span>${alerts.length?`<span class="alert-mark">${alerts.length}</span>`:''}<strong>${s.plate||'빈 자리'}</strong><small>${used(s)?`${s.model} · ${s.color}`:'입차 가능'}</small>${alerts.length?`<span class="alert-text">${alerts.join(' · ')}</span>`:''}</button>`;}
function zoneCard(z,list,renderNow=false){if(!renderNow)return'';const all=state.spots.filter(s=>s.zoneId===z.id),n=all.filter(used).length,shown=z.type==='service'?list.filter(used):list;if(!shown.length)return'';return`<article class="zone-card ${z.type}"><div class="zone-title"><div><span>${z.short}</span><div><h3>${z.name}</h3><small>${z.type==='service'?'서비스 구역':'일반 주차 구역'}</small></div></div><p>${z.type==='service'?`<b>${n}</b>대`:`<b>${n}</b> / ${all.length}대`}</p></div><div class="spot-grid">${shown.map(spot).join('')}</div></article>`;}
function renderParkingWorkspace(){const tabs=document.querySelector('.zone-tabs'),container=document.querySelector('.zones'),legend=document.querySelector('.legend'),selectedZone=zones.find(item=>item.id===state.zone);if(!tabs||!container)return;tabs.innerHTML=`<button data-zone="all" class="${state.zone==='all'?'active':''}">전체</button>`+zones.map(item=>`<button data-zone="${item.id}" class="${selectedZone?.id===item.id?'active':''}">${item.short}</button>`).join('');tabs.querySelectorAll('[data-zone]').forEach(button=>button.onclick=()=>{state.zone=button.dataset.zone;render();});if(legend)legend.innerHTML='<span><i class="dot empty"></i>빈 자리</span><span><i class="dot occupied"></i>주차 중</span><span><i class="dot alert"></i>확인 필요</span><span><i class="dot service"></i>서비스</span><span><i class="dot special"></i>특수 공간</span>';const matches=new Set(visible().map(spot=>spot.id)),renderZone=zone=>{const all=state.spots.filter(spot=>spot.zoneId===zone.id);return parkingLayouts[zone.id]?renderParkingMap(parkingLayouts[zone.id],all,matches,{zoneId:zone.id,expanded:state.expandedLayouts.has(zone.id)}):zoneCard(zone,all.filter(spot=>matches.has(spot.id)),true);};container.innerHTML=state.zone==='all'?zones.map(renderZone).filter(Boolean).join('')||'<div class="no-result"><strong>표시할 주차 구역이 없습니다.</strong></div>':renderZone(selectedZone||zones[0])||'<div class="no-result"><strong>현재 구역에 차량이 없습니다.</strong></div>';container.querySelectorAll('[data-toggle-map]').forEach(button=>button.onclick=()=>{const zoneId=button.dataset.toggleMap;if(state.expandedLayouts.has(zoneId))state.expandedLayouts.delete(zoneId);else state.expandedLayouts.add(zoneId);renderParkingWorkspace();});container.querySelectorAll('.parking-map-grid').forEach(grid=>grid.addEventListener('click',event=>{const cell=event.target.closest('[data-spot]');if(!cell)return;state.selected=cell.dataset.spot;const selected=state.spots.find(spot=>spot.id===state.selected);state.mode=used(selected)?'detail':'assign';render();}));container.querySelectorAll('.zone-card [data-spot]').forEach(cell=>cell.onclick=()=>{state.selected=cell.dataset.spot;const selected=state.spots.find(spot=>spot.id===state.selected);state.mode=used(selected)?'detail':'assign';render();});}
const MANAGERS=['대표님','황정웅대리','권용민주임','김지민대리'];
function managerOptions(current=''){return`<option value="">담당자 선택</option>${MANAGERS.map(name=>`<option value="${name}" ${current===name?'selected':''}>${name}</option>`).join('')}${current&&!MANAGERS.includes(current)?`<option value="${esc(current)}" selected>${esc(current)}</option>`:''}`;}
const VEHICLE_COLORS=['검정','흰색','쥐색','녹색','빨강','파랑','베이지','노랑'];
const colorSelect=value=>`<select name="color" required><option value="">색상을 선택하세요</option>${VEHICLE_COLORS.map(color=>`<option value="${color}" ${normalizeVehicleColor(value)===color?'selected':''}>${color}</option>`).join('')}</select>`;
function vehicleForm(s){const fresh=!used(s),required=fresh?'required':'',today=new Date().toLocaleDateString('en-CA'),checkedInDate=String(s.checkedInAt||today).slice(0,10);return`<form id="vehicle-form"><label>차량번호<input name="plate" value="${esc(s.plate)}" placeholder="123가 4567" required autocomplete="off"></label><label>입고일<input type="date" name="checkedInDate" value="${esc(checkedInDate)}" required></label><div class="form-row"><label>차명<input name="model" value="${esc(s.model)}" ${required}></label><label>연식<input name="modelYear" value="${esc(s.modelYear)}" inputmode="numeric" placeholder="예: 2022" ${required}></label></div><div class="form-row"><label>색상${fresh?colorSelect(s.color):`<input name="color" value="${esc(normalizeVehicleColor(s.color))}" required>`}</label><label>담당자<select name="manager" ${required}>${managerOptions(s.manager)}</select></label></div><label>옵션 <small>(선택)</small><input name="options" value="${esc(s.options)}" maxlength="500" placeholder="주요 옵션"></label><fieldset><legend>확인이 필요한 상태</legend><div class="status-list">${STATUS.map(x=>`<label><input type="checkbox" name="alerts" value="${x.id}" ${s.alerts.includes(x.id)?'checked':''}><span>${x.mark}</span>${x.label}</label>`).join('')}</div></fieldset><div class="modal-actions">${fresh?'<span></span>':`<div><button type="button" class="ghost" data-history>이동 이력</button><button type="button" class="ghost" data-move>위치 이동</button>${s.isUnassigned?'':`<button type="button" class="ghost danger" data-unassign>삭제</button>`}</div>`}<button class="primary" data-save-vehicle ${state.saving||fresh?'disabled':''}>${state.saving?'저장 중…':fresh?'등록':'정보 저장'}</button></div></form>`;}
function moveForm(s){const empty=state.spots.filter(x=>!used(x));return`<form id="move-form"><p class="move-car"><b>${esc(s.plate)}</b><span>${esc(s.model)} · ${esc(s.color)}</span></p><label>이동할 빈 자리<select name="destination" required><option value="">구역과 위치를 선택하세요</option>${zones.map(z=>{const list=empty.filter(x=>x.zoneId===z.id);return list.length?`<optgroup label="${z.name}">${list.map(x=>`<option value="${x.id}">${x.label}</option>`).join('')}</optgroup>`:''}).join('')}</select></label><div class="modal-actions"><button type="button" class="ghost" data-back>취소</button><button class="primary">이동 완료</button></div></form>`;}
function assignSpotForm(s){return`<form id="assign-spot-form"><div class="assign-destination"><span>선택한 빈 자리</span><strong>${esc(s.zone)} · ${esc(s.label)}</strong></div><label class="vehicle-search">차량번호 검색 및 선택<input id="assign-plate-input" name="plate" inputmode="text" autocomplete="off" placeholder="전체 차량번호 또는 끝 4자리를 입력하세요" aria-controls="assign-results" aria-autocomplete="list" required><input type="hidden" id="assign-vehicle-id" name="vehicleId"><div id="assign-results" class="assign-results" role="listbox" aria-live="polite"><p>차량번호를 입력해 주세요.</p></div></label><p class="form-help">차량번호가 보이지 않는다면, 입고 버튼을 통해 신규차량등록상태를 확인해 주세요.</p><div class="modal-actions"><button type="button" class="ghost" data-close>취소</button><button class="primary">저장</button></div></form>`;}
function checkoutForm(){return`<form id="checkout-form"><label class="vehicle-search">출고 차량번호 선택<input id="checkout-plate-input" inputmode="text" autocomplete="off" placeholder="전체 차량번호 또는 끝 4자리를 입력하세요" aria-controls="checkout-results" aria-autocomplete="list" required><input type="hidden" id="checkout-vehicle-id" name="vehicleId"><div id="checkout-results" class="assign-results" role="listbox" aria-live="polite"><p>차량번호를 입력해 주세요.</p></div></label><p class="form-help">현재 주차구역에 배정된 차량만 출고할 수 있습니다.</p><div class="modal-actions"><button type="button" class="ghost" data-close>취소</button><button class="primary" data-checkout-submit disabled>출고</button></div></form>`;}
function historyView(){return`<div class="history-panel" aria-live="polite">${state.loading?'<p>이력을 불러오는 중입니다…</p>':state.history?.length?state.history.map(h=>`<article><b>${h.movement_type}</b><span>${esc(h.from_zone||'입차')} ${esc(h.from_label||'')} → ${esc(h.to_zone||'출차')} ${esc(h.to_label||'')}</span><small>${esc(h.actor_name)} · ${esc(h.created_at)}</small></article>`).join(''):'<p>이동 이력이 없습니다.</p>'}<button class="ghost" data-back>차량 정보로 돌아가기</button></div>`;}
function modal(s){return`<div class="modal-backdrop" data-close><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal><button class="modal-close" data-close aria-label="상세 화면 닫기">×</button>${state.mode==='checkout'?'':`<p class="eyebrow">${s.zone} · ${s.label}</p>`}<h2 id="modal-title">${state.mode==='checkout'?'차량 출고':state.mode==='assign'?'차량번호 선택':state.mode==='move'?'위치 이동':state.mode==='history'?'전체 이동 이력':used(s)?'차량 상세':'신규 입고'}</h2>${state.mode==='checkout'?checkoutForm():state.mode==='assign'?assignSpotForm(s):state.mode==='move'?moveForm(s):state.mode==='history'?historyView():vehicleForm(s)}</section></div>`;}
function renderParking(){const c=stats(),v=visible(),selected=state.spots.find(s=>s.id===state.selected);app.innerHTML=`<header class="topbar"><a class="brand" href="/" aria-label="주식회사 하나오토 주차 위치 현황"><span class="brand-mark">H</span><span><b>(주)하나오토</b><small>HANA AUTO</small></span></a><a class="header-dashboard-link" href="/dashboard">차량 현황판</a></header><main id="top"><div class="demo-banner ${state.backend?'connected':''}" role="status"><b>${state.backend?'D1':'DEMO'}</b>${state.backend?'Cloudflare D1 운영 데이터에 연결됨':'읽기 전용 데모 · 운영 데이터베이스와 연결되지 않음'}</div>${state.loading?'<div class="loading" role="status">주차 현황을 불러오는 중입니다…</div>':''}${state.error?`<div class="toast error" role="alert">${esc(state.error)} <button data-dismiss>닫기</button></div>`:''}${state.notice?`<div class="toast" role="status">${esc(state.notice)}</div>`:''}<section class="parking-title"><p class="eyebrow">PARKING LOCATION</p><h1>주차 위치 현황</h1><div class="hero-buttons"><button class="arrival-button" data-new>입고</button><button class="departure-button" data-out>출고</button></div></section><section class="summary parking-summary">${metric('전체 주차면',c.total,'TOTAL')}${metric('주차 차량',c.occupied,'IN USE','dark')}${metric('빈 자리',c.empty,'AVAILABLE','green')}${metric('확인 필요',c.alerts,'CHECK','amber')}</section><section class="workspace" id="zones"><div class="section-head"><div><p class="eyebrow">PARKING MAP</p><h2>주차 현황</h2></div><p class="updated">● ${state.backend?'직원 간 실시간 공유':'데모 보기'}</p></div><div class="toolbar"><label class="search"><span>⌕</span><span class="sr-only">차량 검색</span><input id="search" value="${esc(state.query)}" placeholder="차량번호 · 차종 · 색상 · 담당자 검색"></label><div class="segmented">${[['all','전체'],['occupied','주차 중'],['empty','빈 자리'],['alert','확인 필요'],['service','서비스']].map(([id,l])=>`<button data-filter="${id}" class="${state.filter===id?'active':''}">${l}</button>`).join('')}</div></div><div class="zone-tabs"><button data-zone="all" class="${state.zone==='all'?'active':''}">전체 구역</button>${zones.map(z=>`<button data-zone="${z.id}" class="${state.zone===z.id?'active':''}">${z.short}</button>`).join('')}</div><div class="legend"><span><i class="dot occupied"></i>주차 중</span><span><i class="dot empty"></i>빈 자리</span><span><i class="dot alert"></i>확인 필요</span></div><div class="zones">${zones.map(z=>zoneCard(z,v.filter(s=>s.zoneId===z.id))).join('')}</div>${v.length?'':'<div class="no-result"><strong>조건에 맞는 차량이나 주차면이 없습니다.</strong><p>검색어 또는 필터를 변경해 주세요.</p><button data-reset>필터 초기화</button></div>'}</section></main><footer><span>(주)하나오토</span><p>현장의 흐름을 더 단순하게.</p><small>${state.backend?'D1 운영 데이터':'읽기 전용 데모 데이터'}</small></footer>${selected?modal(selected):''}`;bind();}
const MANAGER_ORDER=['대표님','황정웅대리','김지민대리','권용민주임','담당자 미지정'];
function boardGroups(){return Object.entries(state.unassigned.reduce((groups,vehicle)=>{const name=vehicle.manager.trim()||'담당자 미지정';if(state.managerFilter!=='all'&&name!==state.managerFilter)return groups;(groups[name]??=[]).push(vehicle);return groups;},{})).sort(([a],[b])=>{const ai=MANAGER_ORDER.indexOf(a),bi=MANAGER_ORDER.indexOf(b);return(ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'ko');});}
function renderDashboard(){const selected=state.spots.find(s=>s.id===state.selected),q=state.query.trim().toLowerCase(),groups=boardGroups().map(([manager,cars])=>[manager,cars.filter(s=>!q||[s.plate,s.model,s.modelYear,s.color,s.options,s.manager].some(v=>String(v).toLowerCase().includes(q)))]).filter(([,cars])=>cars.length),categories=[['all','전체'],['대표님','대표님'],['황정웅대리','황대리'],['김지민대리','김대리'],['권용민주임','권주임']];app.innerHTML=`<header class="topbar"><a class="brand" href="/" aria-label="주차 위치 현황으로 이동"><span class="brand-mark">H</span><span><b>(주)하나오토</b><small>HANA AUTO</small></span></a><nav class="board-nav"><a href="/">주차 위치 현황</a><button data-new>+ 신규 입차</button></nav></header><main class="board-page"><div class="demo-banner ${state.backend?'connected':''}" role="status"><b>${state.backend?'D1':'DEMO'}</b>${state.backend?'Cloudflare D1 운영 데이터에 연결됨':'읽기 전용 데모'}</div>${state.loading?'<div class="loading">차량을 불러오는 중입니다…</div>':''}${state.error?`<div class="toast error" role="alert">${esc(state.error)} <button data-dismiss>닫기</button></div>`:''}${state.notice?`<div class="toast">${esc(state.notice)}</div>`:''}<section class="board-hero"><div><p class="eyebrow">VEHICLE DASHBOARD</p><h1>차량 현황판</h1><p>담당자별 입고 차량을 확인하고 정보를 바로 수정하세요.</p></div><strong>${state.unassigned.length}<small>대</small></strong></section><nav class="manager-tabs" aria-label="담당자별 차량 보기">${categories.map(([id,label])=>`<button data-manager-filter="${id}" class="${state.managerFilter===id?'active':''}">${label}</button>`).join('')}</nav><section class="board-tools"><label class="search"><span>⌕</span><span class="sr-only">차량 검색</span><input id="search" value="${esc(state.query)}" placeholder="차량번호 · 차명 · 담당자 검색"></label><form id="plate-assign-form" class="compact-assign"><label><span class="sr-only">차량번호 뒤 4자리</span><input name="last4" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="번호 뒤 4자리" required></label><button>주차 위치 지정</button></form></section><section class="manager-groups">${groups.length?groups.map(([manager,cars])=>`<article class="manager-group"><header><h2>${esc(manager)}</h2><b>${cars.length}대</b></header><div class="board-table"><div class="board-row board-labels"><span>차량번호</span><span>차명</span><span>연식</span><span>색상</span><span>옵션</span><span class="sr-only">수정</span></div>${cars.map(s=>`<button class="board-row" data-queue="${s.id}" aria-label="${esc(s.plate)} 차량 정보 수정"><strong>${esc(s.plate)}</strong><span>${esc(s.model)||'-'}</span><span>${esc(s.modelYear)||'-'}</span><span>${esc(normalizeVehicleColor(s.color))||'-'}</span><span>${esc(s.options)||'-'}</span><i class="board-edit-icon" aria-hidden="true">✎</i></button>`).join('')}</div></article>`).join(''):'<div class="no-result"><strong>조건에 맞는 차량이 없습니다.</strong></div>'}</section></main>${selected?modal(selected):''}`;bindDashboard();}
function render(){if(location.pathname==='/dashboard'||location.pathname==='/dashboard/')renderDashboard();else renderParking();}
function requireBackend(){if(state.backend)return true;state.error='데이터베이스 연결 전에는 데모 데이터를 변경할 수 없습니다.';render();return false;}
function addExternalTools(){const tools=document.createElement('nav');tools.className='external-tools';tools.setAttribute('aria-label','외부 업무 메뉴');tools.innerHTML='<a href="https://console.humax-parcs.com/store" target="_blank" rel="noopener noreferrer">새싹타워정기권</a><a href="https://www.encar.com/sl/sl_index.do?method=guaranteeSaleInfo" target="_blank" rel="noopener noreferrer">엔카진단예약</a>';document.querySelector('.topbar')?.append(tools);}
function configureFooter(){let footer=document.querySelector('footer');if(!footer){footer=document.createElement('footer');app.append(footer);}footer.innerHTML='<strong>(주)하나오토</strong><div class="company-info"><span>대표자 : 하성은</span><span>사업자번호 : 773-88-03383</span><span>주소 : 서울특별시 강서구 양천로53길 30, 606호</span></div>';}
async function enableNotifications(){if(!requireBackend())return;if(!('serviceWorker'in navigator)||!('PushManager'in window)){state.error='이 브라우저에서는 푸시 알림을 지원하지 않습니다.';render();return;}try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('알림 권한이 허용되지 않았습니다.');const registration=await navigator.serviceWorker.register('/sw.js'),{publicKey}=await api('push/public-key');if(!publicKey)throw new Error('VAPID 공개키가 아직 설정되지 않았습니다.');const bytes=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(publicKey.length/4)*4,'=')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('push/subscribe',{method:'POST',body:JSON.stringify(subscription)});state.notice='푸시 알림을 활성화했습니다.';render();}catch(e){state.error=e.message;render();}}
function addFooterControls(){const controls=document.createElement('div');controls.className='footer-tools';controls.innerHTML='<button class="footer-icon notify-button" aria-label="푸시 알림 설정" title="알림 설정"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg></button><a class="footer-icon admin-link" href="/admin" aria-label="관리자 설정" title="관리자 설정">⚙</a>';document.querySelector('footer')?.append(controls);controls.querySelector('.notify-button')?.addEventListener('click',enableNotifications);}
function bindVehicleAvailability(){const form=document.querySelector('#vehicle-form'),button=form?.querySelector('[data-save-vehicle]'),selected=state.spots.find(spot=>spot.id===state.selected);if(!form||!button||selected?.id!=='draft')return;const update=()=>{button.disabled=state.saving||!['plate','checkedInDate','model','modelYear','color','manager'].every(name=>String(new FormData(form).get(name)||'').trim());};form.addEventListener('input',update);form.addEventListener('change',update);update();}
function bind(){
 addExternalTools();
 configureFooter();
 addFooterControls();
 renderParkingWorkspace();
 renderParkingSearchResults();
 bindVehicleAvailability();
 document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;renderParkingWorkspace();renderParkingSearchResults();});
 document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{state.filter=e.dataset.filter;render();});document.querySelectorAll('[data-zone]').forEach(e=>e.onclick=()=>{state.zone=e.dataset.zone;render();});
 document.querySelectorAll('[data-close]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-modal]')&&!e.target.matches('.modal-close')&&!e.target.matches('[data-close]'))return;state.spots=state.spots.filter(s=>s.id!=='checkout-modal');state.selected=null;state.mode='detail';render();});
 document.querySelectorAll('[data-new]').forEach(el=>el.onclick=()=>{if(!requireBackend())return;state.spots.push({id:'draft',plate:'',model:'',color:'',memo:'',alerts:[],zone:'차량 현황판',label:'신규 입고'});state.selected='draft';state.mode='detail';render();});
 document.querySelectorAll('[data-queue]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.queue;state.mode='detail';render();});
 document.querySelector('#plate-assign-form')?.addEventListener('submit',e=>{e.preventDefault();const last4=String(new FormData(e.currentTarget).get('last4')||''),matches=state.unassigned.filter(s=>s.plate.endsWith(last4));if(matches.length!==1){state.error=matches.length?'같은 끝번호 차량이 여러 대입니다. 현황판 차량을 직접 선택해 주세요.':'해당 끝번호의 미배정 차량이 없습니다.';render();return;}state.selected=matches[0].id;state.mode='move';render();});
 const assignInput=document.querySelector('#assign-plate-input'),assignVehicleId=document.querySelector('#assign-vehicle-id'),assignResults=document.querySelector('#assign-results');
 let assignRequest=0;
 const showAssignMatches=async()=>{if(!assignInput||!assignResults)return;const value=assignInput.value.trim();if(!value){assignResults.innerHTML='<p>전체 차량번호 또는 끝 4자리를 입력해 주세요.</p>';return;}const requestId=++assignRequest;assignResults.innerHTML='<p>차량 이력을 검색하는 중입니다…</p>';try{const matches=(await searchVehicleHistory(value)).filter(vehicle=>!vehicle.checked_out_at&&!vehicle.current_spot_id);if(requestId!==assignRequest)return;assignResults.innerHTML=matches.length?matches.map(vehicle=>`<button type="button" data-assign-id="${esc(vehicle.id)}" data-version="${Number(vehicle.version)||0}" data-plate="${esc(vehicle.plate)}" data-model="${esc(vehicle.model||'')}" data-color="${esc(normalizeVehicleColor(vehicle.color))}"><strong>${esc(vehicle.plate)}</strong><span>${esc(vehicle.model||'차종 미입력')} · ${esc(normalizeVehicleColor(vehicle.color)||'색상 미입력')}</span></button>`).join(''):'<p>일치하는 미배정 차량이 없습니다.</p>';assignResults.querySelectorAll('[data-assign-id]').forEach(button=>button.onclick=()=>{assignInput.value=`${button.dataset.plate} · ${button.dataset.model||'차종 미입력'} · ${button.dataset.color||'색상 미입력'}`;assignVehicleId.value=button.dataset.assignId;assignVehicleId.dataset.version=button.dataset.version;assignVehicleId.dataset.plate=button.dataset.plate;assignResults.innerHTML=`<button type="button" class="is-selected"><strong>${esc(button.dataset.plate)}</strong><span>${esc(button.dataset.model||'차종 미입력')} · ${esc(button.dataset.color||'색상 미입력')}</span></button>`;});}catch(error){if(requestId===assignRequest)assignResults.innerHTML=`<p>${esc(error.message)}</p>`;}};
 assignInput?.addEventListener('input',()=>{assignRequest+=1;if(assignVehicleId){assignVehicleId.value='';assignVehicleId.dataset.version='';assignVehicleId.dataset.plate='';}showAssignMatches();});assignInput?.addEventListener('focus',()=>{if(!assignVehicleId?.value)showAssignMatches();});
 document.querySelector('#assign-spot-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const target=state.spots.find(s=>s.id===state.selected),vehicleId=assignVehicleId?.value,version=Number(assignVehicleId?.dataset.version),plate=assignVehicleId?.dataset.plate;if(!vehicleId){state.error='검색 결과 목록에서 차량을 선택해 주세요.';render();return;}state.saving=true;render();try{await api(`vehicles/${vehicleId}/move`,{method:'POST',body:JSON.stringify({spotId:target.id,version})});await refresh(`${plate} 차량을 ${target.zone} ${target.label}에 배정했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 const checkoutInput=document.querySelector('#checkout-plate-input'),checkoutVehicleId=document.querySelector('#checkout-vehicle-id'),checkoutResults=document.querySelector('#checkout-results'),checkoutSubmit=document.querySelector('[data-checkout-submit]');
 let checkoutRequest=0;
 const showCheckoutMatches=async()=>{if(!checkoutInput||!checkoutResults)return;const value=checkoutInput.value.trim();if(!value){checkoutResults.innerHTML='<p>전체 차량번호 또는 끝 4자리를 입력해 주세요.</p>';return;}const requestId=++checkoutRequest;checkoutResults.innerHTML='<p>차량 이력을 검색하는 중입니다…</p>';try{const matches=(await searchVehicleHistory(value)).filter(vehicle=>!vehicle.checked_out_at&&vehicle.current_spot_id);if(requestId!==checkoutRequest)return;checkoutResults.innerHTML=matches.length?matches.map(vehicle=>`<button type="button" data-checkout-id="${esc(vehicle.id)}" data-plate="${esc(vehicle.plate)}" data-model="${esc(vehicle.model||'')}" data-color="${esc(normalizeVehicleColor(vehicle.color))}"><strong>${esc(vehicle.plate)}</strong><span>${esc(vehicle.model||'차종 미입력')} · ${esc(normalizeVehicleColor(vehicle.color)||'색상 미입력')} · ${esc(vehicle.zone_name||'')} ${esc(vehicle.spot_label||'')}</span></button>`).join(''):'<p>일치하는 주차 차량이 없습니다.</p>';checkoutResults.querySelectorAll('[data-checkout-id]').forEach(button=>button.onclick=()=>{checkoutInput.value=`${button.dataset.plate} · ${button.dataset.model||'차종 미입력'} · ${button.dataset.color||'색상 미입력'}`;checkoutVehicleId.value=button.dataset.checkoutId;checkoutVehicleId.dataset.plate=button.dataset.plate;checkoutSubmit.disabled=false;checkoutResults.innerHTML=`<button type="button" class="is-selected"><strong>${esc(button.dataset.plate)}</strong><span>${esc(button.dataset.model||'차종 미입력')} · ${esc(button.dataset.color||'색상 미입력')}</span></button>`;});}catch(error){if(requestId===checkoutRequest)checkoutResults.innerHTML=`<p>${esc(error.message)}</p>`;}};
 checkoutInput?.addEventListener('input',()=>{checkoutRequest+=1;checkoutVehicleId.value='';checkoutVehicleId.dataset.plate='';checkoutSubmit.disabled=true;showCheckoutMatches();});checkoutInput?.addEventListener('focus',()=>{if(!checkoutVehicleId?.value)showCheckoutMatches();});
 document.querySelector('#checkout-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const vehicleId=checkoutVehicleId.value,plate=checkoutVehicleId.dataset.plate;if(!vehicleId){state.error='목록에서 출고할 차량을 선택해 주세요.';render();return;}checkoutSubmit.disabled=true;state.saving=true;try{await api(`vehicles/${vehicleId}/check-out`,{method:'POST',body:'{}'});await refresh(`${plate} 차량을 출고 처리했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('[data-out]')?.addEventListener('click',()=>{if(!requireBackend())return;state.spots=state.spots.filter(s=>s.id!=='checkout-modal');state.spots.push({id:'checkout-modal',plate:'',model:'',color:'',memo:'',alerts:[],zone:'',label:''});state.selected='checkout-modal';state.mode='checkout';render();});document.querySelector('[data-print]')?.addEventListener('click',()=>print());document.querySelector('[data-dismiss]')?.addEventListener('click',()=>{state.error='';render();});document.querySelector('[data-reset]')?.addEventListener('click',()=>{state.query='';state.zone='all';state.filter='all';render();});document.querySelector('[data-move]')?.addEventListener('click',()=>{state.mode='move';render();});document.querySelector('[data-back]')?.addEventListener('click',()=>{state.mode='detail';render();});
 document.querySelector('[data-history]')?.addEventListener('click',async()=>{const s=state.spots.find(x=>x.id===state.selected);state.mode='history';state.loading=true;render();try{state.history=(await api(`vehicles/${s.vehicleId}/history`)).history;}catch(e){state.error=e.message;}state.loading=false;render();});
 document.querySelector('#vehicle-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const f=new FormData(e.currentTarget),s=state.spots.find(x=>x.id===state.selected),payload={plate:f.get('plate'),checkedInDate:f.get('checkedInDate'),model:f.get('model'),modelYear:f.get('modelYear'),color:f.get('color'),options:f.get('options'),manager:f.get('manager'),memo:s.memo||''},valid=validateVehicle(payload),fresh=s.id==='draft';if(!valid.ok){state.error=valid.message;render();return;}state.saving=true;render();try{if(fresh)await api('vehicles/check-in',{method:'POST',body:JSON.stringify(payload)});else await api(`vehicles/${s.vehicleId}`,{method:'PATCH',body:JSON.stringify({...payload,version:s.vehicleVersion})});await refresh(fresh?'차량 현황판에 입고 등록했습니다.':'차량 정보를 수정했습니다.');}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('#move-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const s=state.spots.find(x=>x.id===state.selected),target=state.spots.find(x=>x.id===new FormData(e.currentTarget).get('destination')),zone=zones.find(z=>z.id===target?.zoneId);state.saving=true;try{await api(`vehicles/${s.vehicleId}/move`,{method:'POST',body:JSON.stringify({spotId:target.id,version:s.vehicleVersion,serviceType:zone?.type==='service'?({polish:'polish',body:'body',repair:'repair'}[zone.id]):null})});await refresh(`${target.zone} ${target.label}(으)로 이동했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('[data-unassign]')?.addEventListener('click',async()=>{if(!requireBackend())return;const s=state.spots.find(x=>x.id===state.selected);state.saving=true;render();try{await api(`vehicles/${s.vehicleId}/unassign`,{method:'POST',body:JSON.stringify({version:s.vehicleVersion})});await refresh(`${s.plate} 차량을 주차구역에서 삭제하고 차량현황판으로 이동했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.onkeydown=e=>{if(e.key==='Escape'&&state.selected){state.spots=state.spots.filter(s=>s.id!=='checkout-modal');state.selected=null;state.mode='detail';render();}};
}
function bindDashboard(){
 addExternalTools();
 configureFooter();
 addFooterControls();
 bindVehicleAvailability();
 document.querySelector('[data-new]')?.addEventListener('click',()=>{if(!requireBackend())return;state.spots.push({id:'draft',plate:'',model:'',modelYear:'',color:'',options:'',manager:'',memo:'',alerts:[],zone:'차량 현황판',label:'신규 입고'});state.selected='draft';state.mode='detail';render();});
 document.querySelectorAll('[data-queue]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.queue;state.mode='detail';render();});
 document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;render();document.querySelector('#search')?.focus();});
 document.querySelectorAll('[data-manager-filter]').forEach(el=>el.addEventListener('click',()=>{state.managerFilter=el.dataset.managerFilter;render();}));
 document.querySelector('#plate-assign-form')?.addEventListener('submit',e=>{e.preventDefault();const last4=String(new FormData(e.currentTarget).get('last4')||''),matches=state.unassigned.filter(s=>s.plate.endsWith(last4));if(matches.length!==1){state.error=matches.length?'같은 끝번호 차량이 여러 대입니다. 목록에서 직접 선택해 주세요.':'해당 끝번호의 차량이 없습니다.';render();return;}state.selected=matches[0].id;state.mode='move';render();});
 document.querySelectorAll('[data-close]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-modal]')&&!e.target.matches('.modal-close'))return;state.selected=null;render();});
 document.querySelector('[data-dismiss]')?.addEventListener('click',()=>{state.error='';render();});document.querySelector('[data-move]')?.addEventListener('click',()=>{state.mode='move';render();});document.querySelector('[data-back]')?.addEventListener('click',()=>{state.mode='detail';render();});
 document.querySelector('#vehicle-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const f=new FormData(e.currentTarget),s=state.spots.find(x=>x.id===state.selected),payload={plate:f.get('plate'),checkedInDate:f.get('checkedInDate'),model:f.get('model'),modelYear:f.get('modelYear'),color:f.get('color'),options:f.get('options'),manager:f.get('manager'),memo:s.memo||''},valid=validateVehicle(payload),fresh=s.id==='draft';if(!valid.ok){state.error=valid.message;render();return;}state.saving=true;render();try{if(fresh)await api('vehicles/check-in',{method:'POST',body:JSON.stringify(payload)});else await api(`vehicles/${s.vehicleId}`,{method:'PATCH',body:JSON.stringify({...payload,version:s.vehicleVersion})});await refresh(fresh?'차량을 등록했습니다.':'차량 정보를 수정했습니다.');}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('#move-form')?.addEventListener('submit',async e=>{e.preventDefault();const s=state.spots.find(x=>x.id===state.selected),target=state.spots.find(x=>x.id===new FormData(e.currentTarget).get('destination')),zone=zones.find(z=>z.id===target?.zoneId);state.saving=true;try{await api(`vehicles/${s.vehicleId}/move`,{method:'POST',body:JSON.stringify({spotId:target.id,version:s.vehicleVersion,serviceType:zone?.type==='service'?({polish:'polish',body:'body',repair:'repair'}[zone.id]):null})});await refresh(`${target.zone} ${target.label}(으)로 이동했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('[data-unassign]')?.addEventListener('click',async()=>{const s=state.spots.find(x=>x.id===state.selected);state.saving=true;render();try{await api(`vehicles/${s.vehicleId}/unassign`,{method:'POST',body:JSON.stringify({version:s.vehicleVersion})});await refresh(`${s.plate} 차량을 주차구역에서 삭제하고 차량현황판으로 이동했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});document.onkeydown=e=>{if(e.key==='Escape'&&state.selected){state.selected=null;render();}};
}
function enableMobilePullToRefresh(){if(!matchMedia('(max-width: 640px)').matches||window.__hanaPullRefresh)return;window.__hanaPullRefresh=true;const indicator=document.createElement('div');indicator.className='pull-refresh';indicator.setAttribute('role','status');indicator.textContent='아래로 당겨 새로고침';document.body.append(indicator);let startX=0,startY=0,distance=0,pulling=false;addEventListener('touchstart',event=>{if(scrollY>0||event.touches.length!==1||event.target.closest('input,select,textarea,.modal'))return;startX=event.touches[0].clientX;startY=event.touches[0].clientY;distance=0;pulling=true;},{passive:true});addEventListener('touchmove',event=>{if(!pulling)return;const x=event.touches[0].clientX-startX,y=event.touches[0].clientY-startY;if(y<=0||Math.abs(x)>y){pulling=false;indicator.classList.remove('visible','ready');return;}distance=Math.min(y*.55,110);if(distance>10)event.preventDefault();indicator.style.transform=`translate(-50%, ${distance-54}px)`;indicator.classList.add('visible');indicator.classList.toggle('ready',distance>=76);indicator.textContent=distance>=76?'놓으면 강력 새로고침':'아래로 당겨 새로고침';},{passive:false});addEventListener('touchend',async()=>{if(!pulling)return;pulling=false;if(distance>=76){indicator.classList.add('refreshing');indicator.textContent='최신 데이터 불러오는 중…';try{if('caches'in window)await Promise.all((await caches.keys()).map(key=>caches.delete(key)));await navigator.serviceWorker?.getRegistration()?.then(registration=>registration?.update());await fetch(location.href,{cache:'reload'});}catch{}location.reload();return;}indicator.classList.remove('visible','ready');indicator.style.transform='translate(-50%, -54px)';},{passive:true});}
async function renderAdmin(){app.innerHTML=`<main class="admin-page"><section class="admin-card"><a href="/" class="admin-back">← 주차 현황</a><p class="eyebrow">SECURE ADMIN</p><h1>(주)하나오토<br><em>관리자 설정</em></h1><div id="admin-status" class="admin-status" role="status">이메일 인증 정보를 확인하는 중입니다…</div><p>Cloudflare Access가 이메일로 전송한 일회용 인증번호를 확인한 기기에서만 관리 기능을 사용할 수 있습니다.</p></section></main>`;try{const result=await api('auth/me');document.querySelector('#admin-status').innerHTML=result.authenticated?`<b>인증 완료</b><span>${esc(result.user.email)} · ${esc(result.user.role)}</span>`:'<b>인증 필요</b><span>Cloudflare Access 이메일 인증을 완료해 주세요.</span>';}catch(e){document.querySelector('#admin-status').innerHTML=`<b>인증 확인 실패</b><span>${esc(e.message)}</span>`;}}
enableMobilePullToRefresh();
if(location.pathname==='/admin'||location.pathname==='/admin/')renderAdmin();else load();
