import './style.css';
import {makeInitialSpots,STATUS,zones} from './data.js';
import {validateVehicle} from './validation.js';

const app=document.querySelector('#app');
const state={spots:[],unassigned:[],query:'',zone:'all',filter:'all',selected:null,mode:'detail',notice:'',error:'',loading:true,backend:false,saving:false};
const used=s=>Boolean(s.plate),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const response=await fetch(`/api/${path}`,{headers:{'Content-Type':'application/json'},...options});const data=await response.json().catch(()=>({message:'서버 응답을 읽을 수 없습니다.'}));if(!response.ok)throw new Error(data.message||'요청을 처리하지 못했습니다.');return data;}
function mapSpot(s){return{id:s.id,zoneId:s.zone_id,zone:s.zone,zoneShort:s.zone_short,label:s.label,plate:s.plate||'',model:s.model||'',color:s.color||'',memo:s.memo||'',alerts:Array.isArray(s.alerts)?s.alerts:JSON.parse(s.alerts||'[]'),updatedAt:s.updated_at||'',vehicleId:s.vehicle_id||null,version:s.version||0,vehicleVersion:s.vehicle_version||0};}
const mapUnassigned=v=>({id:`queue-${v.vehicle_id}`,vehicleId:v.vehicle_id,vehicleVersion:v.vehicle_version,plate:v.plate,model:v.model||'',color:v.color||'',memo:v.memo||'',alerts:[],zone:'차량 현황판',label:'주차 미배정',isUnassigned:true});
async function load(){state.loading=true;render();try{const data=await api('dashboard');state.unassigned=(data.unassigned||[]).map(mapUnassigned);state.spots=[...data.spots.map(mapSpot),...state.unassigned];state.backend=true;state.error='';}catch{state.spots=makeInitialSpots();state.unassigned=[];state.backend=false;state.error='운영 데이터베이스가 아직 연결되지 않아 읽기 전용 데모 데이터를 표시합니다.';}finally{state.loading=false;render();}}
async function refresh(message=''){try{const data=await api('dashboard');state.unassigned=(data.unassigned||[]).map(mapUnassigned);state.spots=[...data.spots.map(mapSpot),...state.unassigned];state.backend=true;state.notice=message;}catch(e){state.error=e.message;}finally{state.saving=false;state.selected=null;render();if(message)setTimeout(()=>{state.notice='';render();},2200);}}
function stats(){const p=state.spots.filter(s=>zones.find(z=>z.id===s.zoneId)?.type==='parking'),n=p.filter(used).length;return{total:p.length,occupied:n,empty:p.length-n,alerts:state.spots.filter(s=>used(s)&&s.alerts.length).length};}
function visible(){const q=state.query.trim().toLowerCase();return state.spots.filter(s=>(state.zone==='all'||s.zoneId===state.zone)&&(state.filter==='all'||(state.filter==='occupied'&&used(s))||(state.filter==='empty'&&!used(s))||(state.filter==='alert'&&s.alerts.length)||(state.filter==='service'&&zones.find(z=>z.id===s.zoneId)?.type==='service'))&&(!q||[s.plate,s.model,s.color,s.label,s.zone,s.memo].some(v=>String(v).toLowerCase().includes(q))));}
const metric=(l,v,en,t='')=>`<article class="metric ${t}"><span>${en}</span><div><strong>${v}</strong><small>${l}</small></div></article>`;
function spot(s){const alerts=s.alerts.map(id=>STATUS.find(x=>x.id===id)?.label).filter(Boolean);return`<button class="spot ${used(s)?'is-used':'is-empty'} ${alerts.length?'has-alert':''}" data-spot="${s.id}" aria-label="${s.zone} ${s.label} ${s.plate||'빈 자리'}"><span class="spot-label">${s.label}</span>${alerts.length?`<span class="alert-mark">${alerts.length}</span>`:''}<strong>${s.plate||'빈 자리'}</strong><small>${used(s)?`${s.model} · ${s.color}`:'입차 가능'}</small>${alerts.length?`<span class="alert-text">${alerts.join(' · ')}</span>`:''}</button>`;}
function zoneCard(z,list){if(!list.length)return'';const all=state.spots.filter(s=>s.zoneId===z.id),n=all.filter(used).length;return`<article class="zone-card ${z.type}"><div class="zone-title"><div><span>${z.short}</span><div><h3>${z.name}</h3><small>${z.type==='service'?'서비스 구역':'일반 주차 구역'}</small></div></div><p><b>${n}</b> / ${all.length}대</p></div><div class="spot-grid">${list.map(spot).join('')}</div></article>`;}
function vehicleForm(s){const fresh=!used(s);return`<form id="vehicle-form"><label>차량번호<input name="plate" value="${esc(s.plate)}" placeholder="123가 4567" required autocomplete="off"></label><div class="form-row"><label>차종<input name="model" value="${esc(s.model)}"></label><label>색상<input name="color" value="${esc(s.color)}"></label></div><label>기타 메모<input name="memo" value="${esc(s.memo)}" maxlength="500"></label><fieldset><legend>확인이 필요한 상태</legend><div class="status-list">${STATUS.map(x=>`<label><input type="checkbox" name="alerts" value="${x.id}" ${s.alerts.includes(x.id)?'checked':''}><span>${x.mark}</span>${x.label}</label>`).join('')}</div></fieldset><div class="modal-actions">${fresh?'<span></span>':`<div><button type="button" class="ghost" data-history>이동 이력</button><button type="button" class="ghost" data-move>위치 이동</button><button type="button" class="ghost danger" data-exit>출차</button></div>`}<button class="primary" ${state.saving?'disabled':''}>${state.saving?'저장 중…':fresh?'입차 등록':'정보 저장'}</button></div></form>`;}
function moveForm(s){const empty=state.spots.filter(x=>!used(x));return`<form id="move-form"><p class="move-car"><b>${esc(s.plate)}</b><span>${esc(s.model)} · ${esc(s.color)}</span></p><label>이동할 빈 자리<select name="destination" required><option value="">구역과 위치를 선택하세요</option>${zones.map(z=>{const list=empty.filter(x=>x.zoneId===z.id);return list.length?`<optgroup label="${z.name}">${list.map(x=>`<option value="${x.id}">${x.label}</option>`).join('')}</optgroup>`:''}).join('')}</select></label><div class="modal-actions"><button type="button" class="ghost" data-back>취소</button><button class="primary">이동 완료</button></div></form>`;}
function historyView(){return`<div class="history-panel" aria-live="polite">${state.loading?'<p>이력을 불러오는 중입니다…</p>':state.history?.length?state.history.map(h=>`<article><b>${h.movement_type}</b><span>${esc(h.from_zone||'입차')} ${esc(h.from_label||'')} → ${esc(h.to_zone||'출차')} ${esc(h.to_label||'')}</span><small>${esc(h.actor_name)} · ${esc(h.created_at)}</small></article>`).join(''):'<p>이동 이력이 없습니다.</p>'}<button class="ghost" data-back>차량 정보로 돌아가기</button></div>`;}
function modal(s){return`<div class="modal-backdrop" data-close><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal><button class="modal-close" data-close aria-label="상세 화면 닫기">×</button><p class="eyebrow">${s.zone} · ${s.label}</p><h2 id="modal-title">${state.mode==='move'?'위치 이동':state.mode==='history'?'전체 이동 이력':used(s)?'차량 상세':'신규 입차'}</h2>${state.mode==='move'?moveForm(s):state.mode==='history'?historyView():vehicleForm(s)}</section></div>`;}
function render(){const c=stats(),v=visible(),selected=state.spots.find(s=>s.id===state.selected);app.innerHTML=`<header class="topbar"><a class="brand" href="#top" aria-label="주식회사 하나오토 홈"><span class="brand-mark">H</span><span><b>(주)하나오토</b><small>HANA AUTO</small></span></a><nav aria-label="주 메뉴"><a href="#dashboard">현황판</a><a href="#zones">구역 관리</a><button data-print>인쇄</button></nav><button class="new-button" data-new>+ 신규 입차</button></header><main id="top"><div class="demo-banner ${state.backend?'connected':''}" role="status"><b>${state.backend?'D1':'DEMO'}</b>${state.backend?'Cloudflare D1 운영 데이터에 연결됨':'읽기 전용 데모 · 운영 데이터베이스와 연결되지 않음'}</div>${state.loading?'<div class="loading" role="status">주차 현황을 불러오는 중입니다…</div>':''}${state.error?`<div class="toast error" role="alert">${esc(state.error)} <button data-dismiss>닫기</button></div>`:''}${state.notice?`<div class="toast" role="status">${esc(state.notice)}</div>`:''}<section class="hero hero-actions" id="dashboard"><p class="eyebrow">FIELD PARKING CONTROL</p><div class="hero-buttons"><button class="arrival-button" data-new>입고</button><button class="departure-button" data-out>출고</button></div></section><section class="summary">${metric('전체 주차면',c.total,'TOTAL')}${metric('주차 차량',c.occupied,'IN USE','dark')}${metric('빈 자리',c.empty,'AVAILABLE','green')}${metric('확인 필요',c.alerts,'CHECK','amber')}</section><section class="workspace" id="zones"><div class="section-head"><div><p class="eyebrow">PARKING MAP</p><h2>주차 현황</h2></div><p class="updated">● ${state.backend?'직원 간 실시간 공유':'데모 보기'}</p></div><div class="toolbar"><label class="search"><span>⌕</span><span class="sr-only">차량 검색</span><input id="search" value="${esc(state.query)}" placeholder="차량번호 · 차종 · 색상 검색"></label><div class="segmented">${[['all','전체'],['occupied','주차 중'],['empty','빈 자리'],['alert','확인 필요'],['service','서비스']].map(([id,l])=>`<button data-filter="${id}" class="${state.filter===id?'active':''}">${l}</button>`).join('')}</div></div><div class="zone-tabs"><button data-zone="all" class="${state.zone==='all'?'active':''}">전체 구역</button>${zones.map(z=>`<button data-zone="${z.id}" class="${state.zone===z.id?'active':''}">${z.short}</button>`).join('')}</div><div class="legend"><span><i class="dot occupied"></i>주차 중</span><span><i class="dot empty"></i>빈 자리</span><span><i class="dot alert"></i>확인 필요</span></div><div class="zones">${zones.map(z=>zoneCard(z,v.filter(s=>s.zoneId===z.id))).join('')}</div>${v.length?'':'<div class="no-result"><strong>조건에 맞는 차량이나 주차면이 없습니다.</strong><p>검색어 또는 필터를 변경해 주세요.</p><button data-reset>필터 초기화</button></div>'}</section></main><footer><span>(주)하나오토</span><p>현장의 흐름을 더 단순하게.</p><small>${state.backend?'D1 운영 데이터':'읽기 전용 데모 데이터'}</small></footer>${selected?modal(selected):''}`;bind();}
function requireBackend(){if(state.backend)return true;state.error='데이터베이스 연결 전에는 데모 데이터를 변경할 수 없습니다.';render();return false;}
function bind(){
 const adminLink=document.createElement('a');adminLink.className='admin-link';adminLink.href='/admin';adminLink.setAttribute('aria-label','관리자 설정');adminLink.textContent='⚙';document.querySelector('.topbar')?.append(adminLink);
 const boardLink=document.createElement('a');boardLink.href='#vehicle-board';boardLink.textContent=`차량 현황판${state.unassigned.length?` (${state.unassigned.length})`:''}`;document.querySelector('.topbar nav')?.prepend(boardLink);
 document.querySelector('.topbar nav')?.remove();document.querySelector('.topbar .new-button')?.remove();
 const board=document.createElement('section');board.id='vehicle-board';board.className='vehicle-board';board.innerHTML=`<div class="board-head"><div><p class="eyebrow">VEHICLE BOARD</p><h2>차량 현황판</h2><p>신규 입고 차량이 먼저 모이는 곳입니다. 차량번호 뒤 4자리로 찾아 주차 위치를 지정하세요.</p></div><strong>${state.unassigned.length}<small>대 미배정</small></strong></div><form id="plate-assign-form" class="plate-assign-form"><label><span>차량번호 뒤 4자리</span><input name="last4" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="예: 9439" required></label><button>주차 위치 지정</button></form><div class="queue-grid">${state.unassigned.length?state.unassigned.map(s=>`<button data-queue="${s.id}"><b>${esc(s.plate)}</b><span>${esc(s.model)} · ${esc(s.color)}</span><small>주차 위치 미배정</small></button>`).join(''):'<p class="queue-empty">주차 위치를 기다리는 입고 차량이 없습니다.</p>'}</div>`;const workspace=document.querySelector('#zones');workspace?.parentNode.insertBefore(board,workspace);
 const tabs=document.createElement('nav');tabs.className='dashboard-tabs';tabs.setAttribute('aria-label','현황 메뉴');tabs.innerHTML=`<a href="#vehicle-board">차량 현황판 <b>${state.unassigned.length}</b></a><a href="#zones">주차 현황</a>`;board.parentNode.insertBefore(tabs,board);
 const notify=document.createElement('button');notify.className='notify-button';notify.textContent='알림 설정';notify.setAttribute('aria-label','푸시 알림 설정');app.append(notify);
 notify.addEventListener('click',async()=>{if(!requireBackend())return;if(!('serviceWorker'in navigator)||!('PushManager'in window)){state.error='이 브라우저에서는 푸시 알림을 지원하지 않습니다.';render();return;}try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('알림 권한이 허용되지 않았습니다.');const registration=await navigator.serviceWorker.register('/sw.js'),{publicKey}=await api('push/public-key');if(!publicKey)throw new Error('VAPID 공개키가 아직 설정되지 않았습니다.');const bytes=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(publicKey.length/4)*4,'=')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('push/subscribe',{method:'POST',body:JSON.stringify(subscription)});state.notice='푸시 알림을 활성화했습니다.';render();}catch(e){state.error=e.message;render();}});
 document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;render();document.querySelector('#search')?.focus();});
 document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{state.filter=e.dataset.filter;render();});document.querySelectorAll('[data-zone]').forEach(e=>e.onclick=()=>{state.zone=e.dataset.zone;render();});
 document.querySelectorAll('[data-spot]').forEach(e=>e.onclick=()=>{state.selected=e.dataset.spot;state.mode='detail';render();});document.querySelectorAll('[data-close]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-modal]')&&!e.target.matches('.modal-close'))return;state.selected=null;render();});
 document.querySelectorAll('[data-new]').forEach(el=>el.onclick=()=>{if(!requireBackend())return;state.spots.push({id:'draft',plate:'',model:'',color:'',memo:'',alerts:[],zone:'차량 현황판',label:'신규 입고'});state.selected='draft';state.mode='detail';render();});
 document.querySelectorAll('[data-queue]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.queue;state.mode='detail';render();});
 document.querySelector('#plate-assign-form')?.addEventListener('submit',e=>{e.preventDefault();const last4=String(new FormData(e.currentTarget).get('last4')||''),matches=state.unassigned.filter(s=>s.plate.endsWith(last4));if(matches.length!==1){state.error=matches.length?'같은 끝번호 차량이 여러 대입니다. 현황판 차량을 직접 선택해 주세요.':'해당 끝번호의 미배정 차량이 없습니다.';render();return;}state.selected=matches[0].id;state.mode='move';render();});
 document.querySelector('[data-out]')?.addEventListener('click',()=>{state.filter='occupied';render();document.querySelector('#zones')?.scrollIntoView({behavior:'smooth'});});document.querySelector('[data-print]')?.addEventListener('click',()=>print());document.querySelector('[data-dismiss]')?.addEventListener('click',()=>{state.error='';render();});document.querySelector('[data-reset]')?.addEventListener('click',()=>{state.query='';state.zone='all';state.filter='all';render();});document.querySelector('[data-move]')?.addEventListener('click',()=>{state.mode='move';render();});document.querySelector('[data-back]')?.addEventListener('click',()=>{state.mode='detail';render();});
 document.querySelector('[data-history]')?.addEventListener('click',async()=>{const s=state.spots.find(x=>x.id===state.selected);state.mode='history';state.loading=true;render();try{state.history=(await api(`vehicles/${s.vehicleId}/history`)).history;}catch(e){state.error=e.message;}state.loading=false;render();});
 document.querySelector('#vehicle-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const f=new FormData(e.currentTarget),s=state.spots.find(x=>x.id===state.selected),payload={plate:f.get('plate'),model:f.get('model'),color:f.get('color'),memo:f.get('memo')},valid=validateVehicle(payload),fresh=s.id==='draft';if(!valid.ok){state.error=valid.message;render();return;}state.saving=true;render();try{if(fresh)await api('vehicles/check-in',{method:'POST',body:JSON.stringify(payload)});else await api(`vehicles/${s.vehicleId}`,{method:'PATCH',body:JSON.stringify({...payload,version:s.vehicleVersion})});await refresh(fresh?'차량 현황판에 입고 등록했습니다.':'차량 정보를 수정했습니다.');}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('#move-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireBackend())return;const s=state.spots.find(x=>x.id===state.selected),target=state.spots.find(x=>x.id===new FormData(e.currentTarget).get('destination')),zone=zones.find(z=>z.id===target?.zoneId);state.saving=true;try{await api(`vehicles/${s.vehicleId}/move`,{method:'POST',body:JSON.stringify({spotId:target.id,version:s.vehicleVersion,serviceType:zone?.type==='service'?({polish:'polish',body:'body',repair:'repair'}[zone.id]):null})});await refresh(`${target.zone} ${target.label}(으)로 이동했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.querySelector('[data-exit]')?.addEventListener('click',async()=>{if(!requireBackend())return;const s=state.spots.find(x=>x.id===state.selected);state.saving=true;render();try{await api(`vehicles/${s.vehicleId}/check-out`,{method:'POST',body:'{}'});await refresh(`${s.plate} 차량을 출차 처리했습니다.`);}catch(err){state.saving=false;state.error=err.message;render();}});
 document.onkeydown=e=>{if(e.key==='Escape'&&state.selected){state.selected=null;render();}};
}
async function renderAdmin(){app.innerHTML=`<main class="admin-page"><section class="admin-card"><a href="/" class="admin-back">← 주차 현황</a><p class="eyebrow">SECURE ADMIN</p><h1>(주)하나오토<br><em>관리자 설정</em></h1><div id="admin-status" class="admin-status" role="status">이메일 인증 정보를 확인하는 중입니다…</div><p>Cloudflare Access가 이메일로 전송한 일회용 인증번호를 확인한 기기에서만 관리 기능을 사용할 수 있습니다.</p></section></main>`;try{const result=await api('auth/me');document.querySelector('#admin-status').innerHTML=result.authenticated?`<b>인증 완료</b><span>${esc(result.user.email)} · ${esc(result.user.role)}</span>`:'<b>인증 필요</b><span>Cloudflare Access 이메일 인증을 완료해 주세요.</span>';}catch(e){document.querySelector('#admin-status').innerHTML=`<b>인증 확인 실패</b><span>${esc(e.message)}</span>`;}}
if(location.pathname==='/admin'||location.pathname==='/admin/')renderAdmin();else load();
